spring.application.name=TicketSystem

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketsystem
spring.datasource.username=postgres
# IMPORTANT: Change this to the password you set during installation
spring.datasource.password=admin

# JPA / Hibernate Settings
# update: Automatically creates or updates the database schema based on our Java classes. Good for development.
spring.jpa.hibernate.ddl-auto=create
# Shows the SQL queries in the console so we can learn what Hibernate is doing
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
